# Server
server.port=8080


# App name shown in logs
spring.application.name=OnlineGroceryOrderSystem

# Thymeleaf ? disable cache during development so HTML changes show immediately
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html


# Show full error details in browser during development
server.error.include-message=always
server.error.include-binding-errors=always

